version: '3'
services:
  dev:
    build: .
    environment:
      - NODE_ENV=dev
    ports:
      - "127.0.0.1:9988:7777"
    command: ["yarn", "start"]

  test:
    build: .
    command: ["yarn", "test"]

